---
AWSTemplateFormatVersion: 2010-09-09
Description: IntSiteCallerUploadHandlerECRRepository

Resources:
  IntSiteCallerUploadHandlerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: intsitecaller-upload-handler
      Tags:
        - Key: "Name"
          Value: "intsitecaller-upload-handler"

Outputs:
  Arn:
    Value: !GetAtt IntSiteCallerUploadHandlerECRRepository.Arn


# aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 483158796244.dkr.ecr.us-east-1.amazonaws.com
# aws cloudformation create-stack --stack-name IntSiteCallerUploadHandlerECRRepository --template-body file://repository.yml  --profile=jdoto-ab3 --region=us-east-1